Solver = cvxpy y la red neuronal tiene el solver incluido en la capa de salida

# Parte 1: obtenemos los datos

In [382]:
import numpy as np
import deep_inv_opt as io
import deep_inv_opt.plot as iop
import torch

import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams['figure.max_open_warning'] = 0  # Let the plots flow!
%matplotlib inline

In [383]:
u_train = io.tensor(np.linspace(-1.5, 1.5, 256).reshape((-1, 1)))
u_train

tensor([[-1.5000],
        [-1.4882],
        [-1.4765],
        [-1.4647],
        [-1.4529],
        [-1.4412],
        [-1.4294],
        [-1.4176],
        [-1.4059],
        [-1.3941],
        [-1.3824],
        [-1.3706],
        [-1.3588],
        [-1.3471],
        [-1.3353],
        [-1.3235],
        [-1.3118],
        [-1.3000],
        [-1.2882],
        [-1.2765],
        [-1.2647],
        [-1.2529],
        [-1.2412],
        [-1.2294],
        [-1.2176],
        [-1.2059],
        [-1.1941],
        [-1.1824],
        [-1.1706],
        [-1.1588],
        [-1.1471],
        [-1.1353],
        [-1.1235],
        [-1.1118],
        [-1.1000],
        [-1.0882],
        [-1.0765],
        [-1.0647],
        [-1.0529],
        [-1.0412],
        [-1.0294],
        [-1.0176],
        [-1.0059],
        [-0.9941],
        [-0.9824],
        [-0.9706],
        [-0.9588],
        [-0.9471],
        [-0.9353],
        [-0.9235],
        [-0.9118],
        [-0.9000],
        [-0.

In [384]:
u_val = io.tensor(np.linspace(-1.5, 1.5, 64).reshape((-1, 1)))
u_val

tensor([[-1.5000],
        [-1.4524],
        [-1.4048],
        [-1.3571],
        [-1.3095],
        [-1.2619],
        [-1.2143],
        [-1.1667],
        [-1.1190],
        [-1.0714],
        [-1.0238],
        [-0.9762],
        [-0.9286],
        [-0.8810],
        [-0.8333],
        [-0.7857],
        [-0.7381],
        [-0.6905],
        [-0.6429],
        [-0.5952],
        [-0.5476],
        [-0.5000],
        [-0.4524],
        [-0.4048],
        [-0.3571],
        [-0.3095],
        [-0.2619],
        [-0.2143],
        [-0.1667],
        [-0.1190],
        [-0.0714],
        [-0.0238],
        [ 0.0238],
        [ 0.0714],
        [ 0.1190],
        [ 0.1667],
        [ 0.2143],
        [ 0.2619],
        [ 0.3095],
        [ 0.3571],
        [ 0.4048],
        [ 0.4524],
        [ 0.5000],
        [ 0.5476],
        [ 0.5952],
        [ 0.6429],
        [ 0.6905],
        [ 0.7381],
        [ 0.7857],
        [ 0.8333],
        [ 0.8810],
        [ 0.9286],
        [ 0.

ahora generamos los x correspondientes del modelo real

In [385]:
class ExamplePLP(io.ParametricLP):
    # Generate an LP from a given feature vector u and weight vector w.
    def generate(self, u, w):
        c = [[torch.cos(w[0] + w[1]*u)],
             [torch.sin(w[0] + w[1]*u)]]

        A_ub = [[-1.0,  0.0],
                [ 0.0, -1.0],
                [ w[0], 1 + w[1]*u/3]]

        b_ub = [[ 0.2*w[0]*u],
                [-0.2*w[1]*u],
                [ w[0] + 0.1*u]]
        
        return c, A_ub, b_ub, None, None

In [386]:
plp_true = ExamplePLP(weights=[1.0, 1.0])

# Generate training targets by solve the true PLP at each u value.
x_train = torch.cat([io.linprog(*plp_true(ui)).detach().t() for ui in u_train])
torch.save(x_train, "x_train.pt")

x_val = torch.cat([io.linprog(*plp_true(ui)).detach().t() for ui in u_val])
torch.save(x_val, "x_val.pt")

In [387]:
x_val = torch.load("x_val.pt")
x_val

tensor([[ 0.3000,  1.1000],
        [ 0.2905,  1.0938],
        [ 0.2810,  1.0880],
        [ 0.2714,  1.0826],
        [ 0.2619,  1.0774],
        [ 0.2524,  1.0726],
        [ 0.2429,  1.0680],
        [ 0.2333,  1.0636],
        [ 0.2238,  1.0594],
        [ 0.2143,  1.0555],
        [ 0.2048,  1.0516],
        [ 0.1952, -0.1950],
        [ 0.1857, -0.1857],
        [ 0.1762, -0.1762],
        [ 0.1667, -0.1666],
        [ 0.1571, -0.1571],
        [ 0.1476, -0.1476],
        [ 0.1381, -0.1381],
        [ 0.1286, -0.1286],
        [ 0.1191, -0.1190],
        [ 0.1095, -0.1095],
        [ 0.1000, -0.1000],
        [ 0.0905, -0.0905],
        [ 0.0810, -0.0809],
        [ 0.0714, -0.0714],
        [ 0.0619, -0.0619],
        [ 0.0524, -0.0524],
        [ 0.0429, -0.0429],
        [ 0.0333, -0.0333],
        [ 0.0238, -0.0238],
        [ 0.0143, -0.0143],
        [ 0.0048, -0.0048],
        [-0.0048,  0.0048],
        [-0.0143,  0.0143],
        [-0.0238,  0.0238],
        [-0.0333,  0

In [388]:
x_train = torch.load("x_train.pt")
x_train

tensor([[ 0.3000,  1.1000],
        [ 0.2977,  1.0984],
        [ 0.2953,  1.0969],
        [ 0.2929,  1.0954],
        [ 0.2906,  1.0939],
        [ 0.2882,  1.0924],
        [ 0.2859,  1.0910],
        [ 0.2835,  1.0896],
        [ 0.2812,  1.0882],
        [ 0.2788,  1.0868],
        [ 0.2765,  1.0854],
        [ 0.2741,  1.0841],
        [ 0.2718,  1.0828],
        [ 0.2694,  1.0815],
        [ 0.2671,  1.0802],
        [ 0.2647,  1.0789],
        [ 0.2624,  1.0777],
        [ 0.2600,  1.0764],
        [ 0.2577,  1.0752],
        [ 0.2553,  1.0740],
        [ 0.2529,  1.0729],
        [ 0.2506,  1.0717],
        [ 0.2482,  1.0705],
        [ 0.2459,  1.0694],
        [ 0.2435,  1.0683],
        [ 0.2412,  1.0672],
        [ 0.2388,  1.0661],
        [ 0.2365,  1.0650],
        [ 0.2341,  1.0640],
        [ 0.2318,  1.0629],
        [ 0.2294,  1.0619],
        [ 0.2271,  1.0608],
        [ 0.2247,  1.0598],
        [ 0.2224,  1.0588],
        [ 0.2200,  1.0579],
        [ 0.2177,  1

# Parte 2: definimos la red y la entrenamos

In [389]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn

In [390]:
# ver si estoy usando GPU
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [391]:
learning_rate = 1e-3
batch_size = 16

In [392]:
# definimos el dataset
class UDataset(Dataset):
    def __init__(self, data, targets):
        self.data = data.clone().to(dtype=torch.float32) # nota: esta dando el warning porque estoy convirtiendo un tensor a otro, en ese caso es mejor usar clone()
        # si los datos de entrada no los voy a dar como un tensor, entonces hay que poner lo que he puesto: self.data = torch.tensor(data, dtype=torch.float32), self.targets = torch.tensor(targets, dtype=torch.float32)
        self.targets = targets.clone().to(dtype=torch.float32)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.targets[idx]

# Dataset con pares (u, x)
dataset = UDataset(u_train, x_train)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [393]:
val_dataset = UDataset(u_val, x_val)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=True)

In [394]:
# funcion que resuelve el problema de programacion lineal (por ahora nos la creemos, pero hay que revisarla)
# hay que tener en cuenta que esta funcion debe realizarse con operaciones de pytorch para
# preservar el grafo de computo para poder hacer backpropagation

def smooth_lp(c, A, b):
    # Inicializar x con gradientes habilitados
    x = torch.zeros(A.shape[1], requires_grad=True)
    optimizer = torch.optim.SGD([x], lr=1e-3)

    for _ in range(1000):
        optimizer.zero_grad()
        constraint_penalty = torch.sum(torch.relu(A @ x - b))
        objective = torch.dot(c, x) + 1000.0 * constraint_penalty
        objective.backward(retain_graph=True)  # Mantén el grafo activo
        optimizer.step()
    return x  # Sin detach()


In [395]:
from diffcp import SolverError
import torch
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer
import contextlib
import io as io2

def solver(c_, A_, b_):
    M = 1000.0
    m,n = A_.shape

    A = cp.Parameter((m, n))
    b = cp.Parameter(m)
    c = cp.Parameter(n)
    x = cp.Variable(n)

    obj = cp.Minimize(c.T @ x + M * cp.sum(cp.pos(A @ x - b))) # cp.pos es max(0, x)
    cons = [ 0*x >= 0 ] # restriccion tonta para que no de error
    prob = cp.Problem(obj, cons)
    layer = CvxpyLayer(prob, parameters=[c,A,b], variables=[x])

    solution, = layer(c_, A_, b_)
    return solution




def solver(c_, A_, b_):
    try:
        M = 1000.0  # Penalización para violaciones de restricciones
        m, n = A_.shape

        A = cp.Parameter((m, n))
        b = cp.Parameter(m)
        c = cp.Parameter(n)
        x = cp.Variable(n)

        # Función objetivo con penalización
        obj = cp.Minimize(c.T @ x + M * cp.sum(cp.pos(A @ x - b)))  

        # Restricción "tonta" para evitar errores con el solver
        cons = [0 * x >= 0]

        prob = cp.Problem(obj, cons)
        layer = CvxpyLayer(prob, parameters=[c, A, b], variables=[x])

        with io2.StringIO() as buf, contextlib.redirect_stdout(buf):
            solution, = layer(c_, A_, b_)
            print(1)
        return solution

    except SolverError:
        print(2)
        return smooth_lp(c_, A_, b_)

# def smooth_lp(c, A, b):
#     ''' 
#     metodo de la M grande pero con descenso 
#     por el grandiente
#     '''
#     # Inicializar x con gradientes habilitados
#     x = torch.zeros(A.shape[1], requires_grad=True)
#     optimizer = torch.optim.SGD([x],lr=0.01, momentum=0.9)

#     for _ in range(100000):
#         optimizer.zero_grad()
#         constraint_penalty = torch.sum(torch.relu(A @ x - b))
#         objective = torch.dot(c, x) + 1000.0 * constraint_penalty
#         objective.backward(retain_graph=True)  # Mantén el grafo activo
#         optimizer.step()
#     return x

# solver = smooth_lp



# voy a probar con el solver del paper
# def solver(c, A, b):
#     ''' 
#     usando el solver del paper
#     '''
#     return io.linprog(c, A, b)
    

In [396]:
plp_true(u_train[0])

[tensor([[ 0.8776],
         [-0.4794]], dtype=torch.float64, grad_fn=<StackBackward0>),
 tensor([[-1.0000,  0.0000],
         [ 0.0000, -1.0000],
         [ 1.0000,  0.5000]], dtype=torch.float64, grad_fn=<StackBackward0>),
 tensor([[-0.3000],
         [ 0.3000],
         [ 0.8500]], dtype=torch.float64, grad_fn=<StackBackward0>),
 None,
 None]

In [397]:
io.linprog(*plp_true(u_train[0]))

tensor([[0.3000],
        [1.1000]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [398]:
c = torch.tensor([-1.0,
                  -1.0], dtype=torch.float64)

A = torch.tensor([[ 1.0000,  0.0000],
                  [ 0.0000,  1.0000]], dtype=torch.float64)

b = torch.tensor([ 0.0,
                   0.0], dtype=torch.float64)

x = solver(c, A, b)

x

tensor([-2.1372e-10, -2.1372e-10], dtype=torch.float64)

Esta version es la red neuronal en la que la resolucion del problema de optimizacion esta dentro de la red

In [399]:
# definimos la red (hay que revisar la forma de la red y el por qué)
class ParametricLPNet(nn.Module):
    def __init__(self):
        super(ParametricLPNet, self).__init__()
        # Entrada de dimensión 1, salida 8 (2 para c, 4 para A, 2 para b)
        self.fc = nn.Sequential(
            nn.Linear(1, 8),
            nn.ReLU(),
            nn.Linear(8, 16),
            nn.ReLU(),
            nn.Linear(16, 8)  # c (2), A (4), b (2)
        )

    def forward(self, u):
        output = self.fc(u)
        # c es un vector 2x1, A es una matriz 2x2, b es un vector 2x1
        
        c = output[:, 0:2]
        A = output[:, 2:6].reshape(-1, 2, 2)
        b = output[:, 6:8]
        return torch.stack([solver(c[i], A[i], b[i]) for i in range(u.shape[0])]) # Resolver LPs ver si hay alguna manera mas eficiente de hacer esto


In [400]:
loss_fn = nn.MSELoss()

In [401]:
# Crear la red neuronal
model = ParametricLPNet()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
# optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) # elegir una de las dos

In [402]:
# para ver el modelo
model

ParametricLPNet(
  (fc): Sequential(
    (0): Linear(in_features=1, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=16, bias=True)
    (3): ReLU()
    (4): Linear(in_features=16, out_features=8, bias=True)
  )
)

In [403]:
# inicializamod los pesos de la red 
def initialize_weights(m):
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight, nonlinearity='leaky_relu') # inicializamos los pesos de la red con Kaiming
        nn.init.zeros_(m.bias) # inicializamos los bias a 0

initialize_weights(model)

In [404]:
def near(rs, x_batch, tol=1e-3):
    '''
    rs: tensor formado por las soluciones de los LPs
    x_batch: tensor formado por las soluciones deseadas de los LPs
    tol: tolerancia para considerar que dos vectores son iguales

    Esta función calcula el número de soluciones de los LPs que están 
    a una distancia menor que tol de las soluciones deseadas.
    '''
    matriz_diferencias = rs - x_batch # matriz de diferencias entre las soluciones de los LPs y las soluciones deseadas
    matriz_al_cuadrado = matriz_diferencias ** 2 # elevo cada elemento al cuadrado
    distancias = torch.sum(matriz_al_cuadrado, dim=1) # sumo los elementos de cada fila
    return torch.sum(distancias < tol).item()

In [405]:
tol = 0.1

def train_loop(dataloader, model, loss_fn, optimizer):
    model.train()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    loss_media = 0.0
    accuracy = 0.0
    batch_size = dataloader.batch_size
    for batch, (u_batch, x_batch) in enumerate(dataloader):

        rs = model(u_batch)
        loss = loss_fn(rs, x_batch) # Calcular la pérdida

        # Backpropagation y optimización
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 8 == 0: # cambiar este numero para que salga cada cierto numero de iteraciones
            loss = loss.item()
            current = batch * batch_size + batch_size
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")
            
        loss_media += loss
        accuracy += near(rs, x_batch, tol)

    return loss_media / num_batches, accuracy / size

In [406]:
def test_loop(dataloader, model, loss_fn):
    model.eval()
    size=len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    #with torch.no_grad():
    for u_batch, x_batch in dataloader:
        rs = model(u_batch)
        test_loss += loss_fn(rs, x_batch).item()
        correct += near(rs, x_batch, tol) # consideramos correcto si se acerca a la solucion en la distancia euclidea 
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n\n")

In [407]:
# Entrenamiento
epochs = 20

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    loss, accuracy = train_loop(dataloader, model, loss_fn, optimizer)
    print(f"\nTraining Error: \n Accuracy: {(100*accuracy):>0.1f}%, Avg loss: {loss:>8f} \n")
    
    test_loop(val_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
loss: 4.608506  [   16/  256]
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
loss: 1.245100  [  144/  256]
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2

Training Error: 
 Accuracy: 0.8%, Avg loss: 1.747054 

2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
Test Error: 
 Accuracy: 3.1%, Avg loss: 0.627514 


Epoch 2
-------------------------------
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
loss: 0.687597  [   16/  256]
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2


KeyboardInterrupt: 

In [204]:
torch.save(model.state_dict(), "model_weights.pth")

In [207]:
model(torch.tensor([[1.5]]))

tensor([[0.5331, 0.4768]], grad_fn=<StackBackward0>)

In [208]:
u_test = torch.tensor(np.linspace(0.1, 4, 16).reshape((-1, 1)), dtype=torch.float64)
u_test

tensor([[0.1000],
        [0.3600],
        [0.6200],
        [0.8800],
        [1.1400],
        [1.4000],
        [1.6600],
        [1.9200],
        [2.1800],
        [2.4400],
        [2.7000],
        [2.9600],
        [3.2200],
        [3.4800],
        [3.7400],
        [4.0000]], dtype=torch.float64)

ahora probamos como funciona para un x nuevo

In [209]:
x_test = torch.cat([io.linprog(*plp_true(ui)).detach().t() for ui in u_test])
x_test

tensor([[-0.0200,  0.0200],
        [-0.0720,  0.0720],
        [ 0.9123,  0.1240],
        [ 0.8604,  0.1760],
        [ 0.7993,  0.2280],
        [ 0.7293,  0.2800],
        [ 0.6503,  0.3320],
        [ 0.5622,  0.3840],
        [ 0.4652,  0.4360],
        [ 0.3591,  0.4880],
        [ 0.2440,  0.5400],
        [ 0.1199,  0.5920],
        [-0.0133,  0.6440],
        [-0.6960,  0.9463],
        [-0.7480,  0.9445],
        [-0.8000,  0.9429]], dtype=torch.float64)

In [210]:
model.eval()

ParametricLPNet(
  (fc): Sequential(
    (0): Linear(in_features=1, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=16, bias=True)
    (3): ReLU()
    (4): Linear(in_features=16, out_features=8, bias=True)
  )
)

In [211]:
u = torch.tensor([[0.25]], dtype=torch.float64)
x = torch.cat([io.linprog(*plp_true(ui)).detach().t() for ui in u])
u,x

(tensor([[0.2500]], dtype=torch.float64),
 tensor([[-0.0500,  0.0500]], dtype=torch.float64))

In [215]:
x_pred = model(torch.tensor([[0.25]]))
x_pred

tensor([[0.0282, 0.1062]], grad_fn=<StackBackward0>)

In [216]:
x, x_pred, torch.norm(x - x_pred)

(tensor([[-0.0500,  0.0500]], dtype=torch.float64),
 tensor([[0.0282, 0.1062]], grad_fn=<StackBackward0>),
 tensor(0.0962, dtype=torch.float64, grad_fn=<LinalgVectorNormBackward0>))